### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Kermit831** [THEMVFFINMAN/RedEraser#1]
I'm a total noob.  I've never installed Python before.  I think I followed each of your steps for Windows.

I'm getting an error when I run RedEraser.py
File |C:\Python34\Scripts\RedEraser.py", line 4
  <!DOCTYPE html>
   ^
SyntaxError: invalid Syntax

**Comment by THEMVFFINMAN** [comment]
The code error is from the beginning of an html document. Now here on this Python code is html code so I'm not sure how you got that. 

It does say that you ran it from Python 3 and as stated, this code does not run on Python 3 but only on Python 2

**Comment by Kermit831** [comment]
Wow!

Thanks for the quick response.  Got it working after I put in Python 2.  I also used your zip file, instead of saving the RedEraser.py by alone.  Which was a weird need, since I was able to save the get-pip.py with a right-click, save link as... And it worked great. 

Thanks for the app, thanks for the assist.

**Comment by THEMVFFINMAN** [comment]
Not a problem. I was really confused at first but Python 3 errors are never
very helpful haha
