### ISSUE TITLE
0 posts deleted, deleting many more than 0.

### ISSUE THREAD

**Issue by Rika-chan** [THEMVFFINMAN/RedEraser#2]
using python 2.7.3, I entered delete 3 comments and 3 posts.

https://gist.github.com/Rika-chan/6db9b5e16fd429ba512f

It ended up deleting more than 0, and not 3 either.

**Comment by THEMVFFINMAN** [comment]
The gist is deprecated, I'm not sure how behind it was on development. If you get the same problems using the github version, I'll look into it for you.
